version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: lis_form
   entrypoint: /bin/sh
   ports:
     - 5173:5173
   working_dir: /app
   volumes:
     - type: bind
       source: ./
       target: /app
   tty: true